name: Update version & publish to npm

on:
   push:
      branches:
         - 'master'

jobs:
   puplish:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v2

         - name: bump version and create tag
           uses: 'phips28/gh-action-bump-version@master'
           env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           with:
              minor-wording: 'feat,feature'

         - name: install node
           uses: actions/setup-node@v1
           with:
              node-version: 10

         - run: npm install

         - run: npm test

         - run: npm run build

         - uses: JS-DevTools/npm-publish@v1
           with:
              token: ${{ secrets.NPM_TOKEN }}
